### ISSUE TITLE
Build ubuntu packages

### ISSUE THREAD

**Issue by mortenlj** [z3ntu/libopenrazer#3]
The ubuntu package for razergenie depends on libopenrazer, but there is no ubuntu package for libopenrazer.

Tried looking at SBS, and it looks like it should be built, but can't find any on the download page.

**Comment by z3ntu** [comment]
What Ubuntu version are you on? The package should be available in the same repo as RazerGenie for Ubuntu 22.04, 22.10, 23.04, 23.10 and 24.04, so the one listed in probably `/etc/apt/sources.list.d/hardware:razer.list`

Specifically the package names in the repo are ~~`libopenrazer`,~~ `libopenrazer0` and `libopenrazer-dev`

**Comment by mortenlj** [comment]
My bad, seems I must have messed up the install instructions. Tried again today, and now it works. :shrug: 

Got confused because the build doesn't show up here: 
https://software.opensuse.org//download.html?project=hardware%3Arazer&package=libopenrazer

Thanks for setting me straight :+1:

**Comment by z3ntu** [comment]
Yeah these download pages are not super simple.

But since in the Debian/Ubuntu repo there's no `libopenrazer` package, just `libopenrazer0` and `libopenrazer-dev`, the download page for the package called `libopenrazer` Debian/Ubuntu doesn't show up.

But it does show up for https://software.opensuse.org//download.html?project=hardware%3Arazer&package=libopenrazer0 and https://software.opensuse.org//download.html?project=hardware%3Arazer&package=libopenrazer-dev then.
